export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  matches: '/matches',
  matchDetail: (id: string) => `/matches/${id}`,
  predictions: '/predictions',
  coupons: '/coupons',
  couponCreate: '/coupons/create',
  couponDetail: (id: string) => `/coupons/${id}`,
  history: '/history',
  favorites: '/favorites',
  profile: '/profile',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminMatches: '/admin/matches',
  adminAnalytics: '/admin/analytics',
  adminAiUsage: '/admin/ai-usage',
} as const;
